In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import requests
import time
import pickle
import json

In [2]:
df = pd.read_parquet("..\data\speaker_attributes.parquet")
df = df[~df['nationality'].isnull()]

# ON ACTUAL DATA

In [3]:
filename = os.listdir('../extracted_data')[0]
print("Considered file : " + "'" + filename +"'")
file = open("../extracted_data/{}".format(filename), "rb")
dict_df = pickle.load(file)

Considered file : 'output_2019 speakers_False keywords_['hurricane', 'climate change'].pickle'

In [4]:
considered_df = dict_df['hurricane']
considered_df

,quoteID,quotation,speaker,qids,date,probas,numOccurences,phase,numOccurrences,urls
1,2019-02-27-008811,"As governor of Florida, I saw firsthand the de...",Rick Scott,[Q439729],2019-02-27 14:45:02,"[[Rick Scott, 0.6951], [None, 0.3049]]",NaN,E,1.0,[http://sunshinestatenews.com/story/marco-rubi...
2,2019-09-02-052055,The core of extremely dangerous Hurricane Dori...,Lixion Avila,[Q6659951],2019-09-02 09:26:48,"[[Lixion Avila, 0.7926], [None, 0.2074]]",NaN,E,1.0,[https://www.prisonplanet.com/watch-as-cat-5-d...
3,2019-05-09-131870,Why go to school if we won't have a future? Wh...,None,[],2019-05-09 05:00:00,"[[None, 0.8667], [Alexandria Ocasio-Cortez, 0....",NaN,E,2.0,[https://www.americanthinker.com/articles/2019...
4,2019-12-30-067171,Will 2020 give Florida a break in hurricane se...,Scott Miller,"[Q1091242, Q14946888, Q21285379, Q22081252, Q3...",2019-12-30 00:00:00,"[[Scott Miller, 0.7189], [None, 0.2535], [Andr...",NaN,E,1.0,[https://floridapolitics.com/archives/314344-s...
5,2019-08-29-106120,We could see a weakening hurricane staying inl...,Michael Brennan,"[Q16106188, Q16195914, Q3077022, Q3313235, Q58...",2019-08-29 22:00:00,"[[Michael Brennan, 0.5289], [None, 0.353], [Do...",NaN,E,1.0,[http://www.nola.com/news/hurricane/article_33...
...,...,...,...,...,...,...,...,...,...,...
5195,2019-02-20-078267,Probably almost half our land was covered by w...,George Brown,"[Q16089648, Q16769694, Q19757618, Q19845109, Q...",2019-02-20 22:31:50,"[[George Brown, 0.7721], [None, 0.1925], [Bill...",NaN,E,1.0,[https://www.wwaytv3.com/2019/02/20/local-lead...
5196,2019-02-15-112277,"We are used to hurricanes, but nothing like wh...",María Meléndez,[Q6782079],2019-02-15 19:02:00,"[[María Meléndez, 0.6994], [None, 0.3006]]",NaN,E,2.0,[https://www.nbcnews.com/news/latino/puerto-ri...
5197,2019-08-30-005357,"And no, I don't wish anyone, anywhere, the hor...",Kim Campbell,"[Q128553, Q6408424]",2019-08-30 14:08:12,"[[Kim Campbell, 0.8485], [None, 0.1445], [Pres...",NaN,E,1.0,[https://www.theblaze.com/news/former-prime-mi...
5198,2019-10-13-041713,The bad news is we are not at all on the right...,Jean-Pascal Tricoire,[Q3168302],2019-10-13 13:00:00,"[[Jean-Pascal Tricoire, 0.3568], [Spencer Dale...",NaN,E,7.0,[http://www.brisbanetimes.com.au/business/the-...
5199,2019-09-06-017079,Dorian should remain a powerful hurricane as i...,None,[],2019-09-06 09:50:54,"[[None, 0.6442], [Ray Cooper, 0.3558]]",NaN,E,1.0,[http://thestreet.com/world/north-carolina-bra...

In [5]:
dict_code_count = {}

for element in considered_df['qids']:
    if len(element) > 0:
        speaker_id = element[0]
        #print(speaker_id)
        nationalities = df[df['id'] == speaker_id]['nationality']
        #print(nationalities)
        # if not nationalities.empty:
        if not nationalities.empty:
            print(nationalities)
            main_nationality = nationalities.iloc[0][0]
            #print(main_nationality)
            if main_nationality in dict_code_count:
                dict_code_count[main_nationality] += 1
            else :
                dict_code_count[main_nationality] = 1

5676513    [Q30]
Name: nationality, dtype: object
6974077    [Q30]
Name: nationality, dtype: object
36237    [Q30]
Name: nationality, dtype: object
2560402    [Q145]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
1544365    [Q145]
Name: nationality, dtype: object
6800188    [Q30]
Name: nationality, dtype: object
7130723    [Q30]
Name: nationality, dtype: object
2845481    [Q30]
Name: nationality, dtype: object
4593342    [Q30]
Name: nationality, dtype: object
2406530    [Q408]
Name: nationality, dtype: object
3409344    [Q45]
Name: nationality, dtype: object
6974077    [Q30]
Name: nationality, dtype: object
2266903    [Q30]
Name: nationality, dtype: object
34940    [Q96]
Name: nationality, dtype: object
3699814    [Q30]
Name: nationality, dtype: object
8433638    [Q145]
Name: nationality, dtype: object
6804699    [Q30]
Name: nationality, dtype: object
4615467    [Q30]
Name: nationality, dtype: object
249709    [Q30]
Name: nationality, dtype: object
5728827    [Q30]
Name: nationality, dtype: object
4723189    [Q30]
Name: nationality, dtype: object
4814973    [Q408]
Name: nationality, dtype: object
3735664    [Q29]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
2709069    [Q1039]
Name: nationality, dtype: object
7944141    [Q30]
Name: nationality, dtype: object
8487    [Q30]
Name: nationality, dtype: object
5676926    [Q30]
Name: nationality, dtype: object
4615467    [Q30]
Name: nationality, dtype: object
2492114    [Q145]
Name: nationality, dtype: object
5830927    [Q30]
Name: nationality, dtype: object
7926982    [Q30]
Name: nationality, dtype: object
318703    [Q145]
Name: nationality, dtype: object
2826317    [Q30]
Name: nationality, dtype: object
4828605    [Q30]
Name: nationality, dtype: object
1135072    [Q838261, Q37024, Q403, Q83286]
Name: nationality, dtype: object
4679653    [Q408]
Name: nationality, dtype: object
3801872    [Q30]
Name: nationality, dtype: object
1408516    [Q183]
Name: nationality, dtype: object
1716495    [Q30]
Name: nationality, dtype: object
205989    [Q664]
Name: nationality, dtype: object
4615467    [Q30]
Name: nationality, dtype: object
8065367    [Q27]
Name: nationality, dtype: object
3458934    [Q30]
Name: nationality, dtype: object
5958639    [Q16]
Name: nationality, dtype: object
4615467    [Q30]
Name: nationality, dtype: object
5972129    [Q778]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
4544778    [Q30]
Name: nationality, dtype: object
7340647    [Q145]
Name: nationality, dtype: object
2600870    [Q30]
Name: nationality, dtype: object
4569795    [Q766]
Name: nationality, dtype: object
3844945    [Q30]
Name: nationality, dtype: object
38487    [Q145]
Name: nationality, dtype: object
1428757    [Q30]
Name: nationality, dtype: object
6949007    [Q30]
Name: nationality, dtype: object
2366229    [Q30]
Name: nationality, dtype: object
2267268    [Q30]
Name: nationality, dtype: object
14909    [Q30]
Name: nationality, dtype: object
4530239    [Q96]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
4920516    [Q30]
Name: nationality, dtype: object
6813121    [Q30]
Name: nationality, dtype: object
4689382    [Q414]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
2543285    [Q30]
Name: nationality, dtype: object
394220    [Q800]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
3455261    [Q30]
Name: nationality, dtype: object
4828447    [Q30]
Name: nationality, dtype: object
5721634    [Q30]
Name: nationality, dtype: object
6793437    [Q183, Q30]
Name: nationality, dtype: object
1268595    [Q30]
Name: nationality, dtype: object
5830927    [Q30]
Name: nationality, dtype: object
5705060    [Q30]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
2273258    [Q16]
Name: nationality, dtype: object
7963055    [Q408]
Name: nationality, dtype: object
7979902    [Q30]
Name: nationality, dtype: object
2418399    [Q30]
Name: nationality, dtype: object
7950388    [Q30]
Name: nationality, dtype: object
6900509    [Q30]
Name: nationality, dtype: object
133685    [Q30]
Name: nationality, dtype: object
8065367    [Q27]
Name: nationality, dtype: object
6803518    [Q30]
Name: nationality, dtype: object
14593    [Q30]
Name: nationality, dtype: object
7961172    [Q30]
Name: nationality, dtype: object
4529845    [Q30]
Name: nationality, dtype: object
5934564    [Q30]
Name: nationality, dtype: object
3844945    [Q30]
Name: nationality, dtype: object
4719936    [Q145]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
2520598    [Q145]
Name: nationality, dtype: object
6800188    [Q30]
Name: nationality, dtype: object
2286727    [Q30]
Name: nationality, dtype: object
1143611    [Q30]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
6931704    [Q30]
Name: nationality, dtype: object
344245    [Q408]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
6800188    [Q30]
Name: nationality, dtype: object
2403125    [Q30]
Name: nationality, dtype: object
2302237    [Q145]
Name: nationality, dtype: object
5676513    [Q30]
Name: nationality, dtype: object
1428757    [Q30]
Name: nationality, dtype: object
7926567    [Q30]
Name: nationality, dtype: object
7091672    [Q30]
Name: nationality, dtype: object
1415755    [Q16]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
6974077    [Q30]
Name: nationality, dtype: object
1267753    [Q30]
Name: nationality, dtype: object
2267860    [Q717]
Name: nationality, dtype: object
3593697    [Q145]
Name: nationality, dtype: object
167369    [Q30]
Name: nationality, dtype: object
7926498    [Q30]
Name: nationality, dtype: object
3530896    [Q30]
Name: nationality, dtype: object
7943182    [Q30]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
2273832    [Q30]
Name: nationality, dtype: object
1267753    [Q30]
Name: nationality, dtype: object
3503413    [Q29, Q30]
Name: nationality, dtype: object
2600870    [Q30]
Name: nationality, dtype: object
1161430    [Q30]
Name: nationality, dtype: object
3538800    [Q30]
Name: nationality, dtype: object
3468995    [Q30]
Name: nationality, dtype: object
2451106    [Q244]
Name: nationality, dtype: object
4615467    [Q30]
Name: nationality, dtype: object
7374515    [Q30]
Name: nationality, dtype: object
3781359    [Q29]
Name: nationality, dtype: object
2555122    [Q408]
Name: nationality, dtype: object
3844945    [Q30]
Name: nationality, dtype: object
4596388    [Q183]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
4544909    [Q30]
Name: nationality, dtype: object
5938498    [Q30]
Name: nationality, dtype: object
4877382    [Q30]
Name: nationality, dtype: object
3444462    [Q145, Q30]
Name: nationality, dtype: object
4679653    [Q408]
Name: nationality, dtype: object
7120050    [Q145]
Name: nationality, dtype: object
5972129    [Q778]
Name: nationality, dtype: object
7969149    [Q30]
Name: nationality, dtype: object
3626868    [Q30]
Name: nationality, dtype: object
1293947    [Q30]
Name: nationality, dtype: object
5972129    [Q778]
Name: nationality, dtype: object
3409344    [Q45]
Name: nationality, dtype: object
6964866    [Q30]
Name: nationality, dtype: object
7972109    [Q408]
Name: nationality, dtype: object
2823318    [Q34]
Name: nationality, dtype: object
1497470    [Q408]
Name: nationality, dtype: object
3409344    [Q45]
Name: nationality, dtype: object
4730937    [Q1033]
Name: nationality, dtype: object
6800188    [Q30]
Name: nationality, dtype: object
6982788    [Q739]
Name: nationality, dtype: object
2540849    [Q29]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
8094494    [Q30]
Name: nationality, dtype: object
300729    [Q30]
Name: nationality, dtype: object
5680529    [Q30]
Name: nationality, dtype: object
1143920    [Q30]
Name: nationality, dtype: object
5701267    [Q30]
Name: nationality, dtype: object
2586485    [Q928]
Name: nationality, dtype: object
8133415    [Q30]
Name: nationality, dtype: object
6801900    [Q30]
Name: nationality, dtype: object
3398127    [Q30]
Name: nationality, dtype: object
6900509    [Q30]
Name: nationality, dtype: object
1433854    [Q30]
Name: nationality, dtype: object
5704651    [Q258]
Name: nationality, dtype: object
4711942    [Q30]
Name: nationality, dtype: object
1405684    [Q30]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
6829078    [Q30]
Name: nationality, dtype: object
7938541    [Q30]
Name: nationality, dtype: object
4656403    [Q30]
Name: nationality, dtype: object
6931704    [Q30]
Name: nationality, dtype: object
6828936    [Q145]
Name: nationality, dtype: object
7168510    [Q30]
Name: nationality, dtype: object
167369    [Q30]
Name: nationality, dtype: object
8274985    [Q30]
Name: nationality, dtype: object
7185851    [Q21]
Name: nationality, dtype: object
5830927    [Q30]
Name: nationality, dtype: object
300729    [Q30]
Name: nationality, dtype: object
4680571    [Q30]
Name: nationality, dtype: object
8487    [Q30]
Name: nationality, dtype: object
5853852    [Q30]
Name: nationality, dtype: object
2560402    [Q145]
Name: nationality, dtype: object
2675426    [Q30]
Name: nationality, dtype: object
98078    [Q30]
Name: nationality, dtype: object
2273258    [Q16]
Name: nationality, dtype: object
7938257    [Q30]
Name: nationality, dtype: object
12632    [Q16]
Name: nationality, dtype: object
1142441    [Q145]
Name: nationality, dtype: object
3527193    [Q30]
Name: nationality, dtype: object
100558    [Q668, Q129286, Q1775277]
Name: nationality, dtype: object
7071825    [Q30]
Name: nationality, dtype: object
9873    [Q30]
Name: nationality, dtype: object
1569058    [Q408]
Name: nationality, dtype: object
2320706    [Q30]
Name: nationality, dtype: object
2296153    [Q114]
Name: nationality, dtype: object
6936410    [Q30]
Name: nationality, dtype: object
2550788    [Q30]
Name: nationality, dtype: object
6881391    [Q30]
Name: nationality, dtype: object
5830927    [Q30]
Name: nationality, dtype: object
6951804    [Q30]
Name: nationality, dtype: object
8056120    [Q30]
Name: nationality, dtype: object
7961164    [Q30]
Name: nationality, dtype: object
5660581    [Q30, Q41]
Name: nationality, dtype: object
7087845    [Q408]
Name: nationality, dtype: object
2675426    [Q30]
Name: nationality, dtype: object
7092837    [Q760]
Name: nationality, dtype: object
4529833    [Q1183]
Name: nationality, dtype: object
7938541    [Q30]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
248642    [Q145]
Name: nationality, dtype: object
8226022    [Q30]
Name: nationality, dtype: object
3844945    [Q30]
Name: nationality, dtype: object
5661693    [Q790]
Name: nationality, dtype: object
7943182    [Q30]
Name: nationality, dtype: object
4557602    [Q145]
Name: nationality, dtype: object
5954435    [Q16]
Name: nationality, dtype: object
2281597    [Q145]
Name: nationality, dtype: object
7093573    [Q30]
Name: nationality, dtype: object
1412472    [Q145]
Name: nationality, dtype: object
8084783    [Q298]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
6974077    [Q30]
Name: nationality, dtype: object
3464091    [Q16]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
8227215    [Q30]
Name: nationality, dtype: object
1478221    [Q145]
Name: nationality, dtype: object
3696992    [Q30]
Name: nationality, dtype: object
61067    [Q16]
Name: nationality, dtype: object
4615467    [Q30]
Name: nationality, dtype: object
8065778    [Q30]
Name: nationality, dtype: object
2396020    [Q30]
Name: nationality, dtype: object
4610385    [Q16]
Name: nationality, dtype: object
4615467    [Q30]
Name: nationality, dtype: object
3586231    [Q30]
Name: nationality, dtype: object
3528958    [Q30]
Name: nationality, dtype: object
2402516    [Q30]
Name: nationality, dtype: object
4615467    [Q30]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
1265168    [Q30]
Name: nationality, dtype: object
2342038    [Q183]
Name: nationality, dtype: object
1520738    [Q30]
Name: nationality, dtype: object
6801963    [Q30]
Name: nationality, dtype: object
7163105    [Q414]
Name: nationality, dtype: object
48999    [Q408]
Name: nationality, dtype: object
7186958    [Q778]
Name: nationality, dtype: object
6092211    [Q142]
Name: nationality, dtype: object
6949007    [Q30]
Name: nationality, dtype: object
4544778    [Q30]
Name: nationality, dtype: object
7091672    [Q30]
Name: nationality, dtype: object
2273258    [Q16]
Name: nationality, dtype: object
5843570    [Q145]
Name: nationality, dtype: object
6830875    [Q766]
Name: nationality, dtype: object
8224443    [Q30]
Name: nationality, dtype: object
300729    [Q30]
Name: nationality, dtype: object
7168478    [Q155]
Name: nationality, dtype: object
4543169    [Q30]
Name: nationality, dtype: object
7964154    [Q30]
Name: nationality, dtype: object
223872    [Q145]
Name: nationality, dtype: object
4829908    [Q145]
Name: nationality, dtype: object
2291402    [Q145]
Name: nationality, dtype: object
4908846    [Q30]
Name: nationality, dtype: object
7981805    [Q27]
Name: nationality, dtype: object
7219359    [Q32]
Name: nationality, dtype: object
100558    [Q668, Q129286, Q1775277]
Name: nationality, dtype: object
140699    [Q30]
Name: nationality, dtype: object
6792739    [Q30]
Name: nationality, dtype: object
6800188    [Q30]
Name: nationality, dtype: object
1276725    [Q30]
Name: nationality, dtype: object
4811801    [Q145]
Name: nationality, dtype: object
3410576    [Q145]
Name: nationality, dtype: object
6949007    [Q30]
Name: nationality, dtype: object
5972129    [Q778]
Name: nationality, dtype: object
5670467    [Q30, Q865]
Name: nationality, dtype: object
6926413    [Q30]
Name: nationality, dtype: object
6974077    [Q30]
Name: nationality, dtype: object
7946443    [Q30]
Name: nationality, dtype: object
4940214    [Q30]
Name: nationality, dtype: object
1135835    [Q30]
Name: nationality, dtype: object
4599819    [Q786]
Name: nationality, dtype: object
338917    [Q30]
Name: nationality, dtype: object
5972129    [Q778]
Name: nationality, dtype: object
3409344    [Q45]
Name: nationality, dtype: object
4615467    [Q30]
Name: nationality, dtype: object
5660857    [Q30]
Name: nationality, dtype: object
2573362    [Q16]
Name: nationality, dtype: object
5830927    [Q30]
Name: nationality, dtype: object
8113367    [Q30]
Name: nationality, dtype: object
87979    [Q16]
Name: nationality, dtype: object
5676926    [Q30]
Name: nationality, dtype: object
3566998    [Q30]
Name: nationality, dtype: object
8033256    [Q29]
Name: nationality, dtype: object
1267753    [Q30]
Name: nationality, dtype: object
5864111    [Q16]
Name: nationality, dtype: object
2712008    [Q142]
Name: nationality, dtype: object
3421256    [Q778]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
1525316    [Q16]
Name: nationality, dtype: object
1143979    [Q30]
Name: nationality, dtype: object
6183470    [Q30]
Name: nationality, dtype: object
1174942    [Q408]
Name: nationality, dtype: object
2274385    [Q16]
Name: nationality, dtype: object
8224829    [Q30]
Name: nationality, dtype: object
5715309    [Q30]
Name: nationality, dtype: object
3679583    [Q30]
Name: nationality, dtype: object
6800325    [Q30]
Name: nationality, dtype: object
1172018    [Q30]
Name: nationality, dtype: object
1574208    [Q30]
Name: nationality, dtype: object
5676513    [Q30]
Name: nationality, dtype: object
4721285    [Q30]
Name: nationality, dtype: object
5669383    [Q145]
Name: nationality, dtype: object
5714218    [Q30]
Name: nationality, dtype: object
4697131    [Q30]
Name: nationality, dtype: object
6801077    [Q145]
Name: nationality, dtype: object
2435896    [Q30]
Name: nationality, dtype: object
5972129    [Q778]
Name: nationality, dtype: object
4718306    [Q145]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
1445920    [Q30]
Name: nationality, dtype: object
538996    [Q30]
Name: nationality, dtype: object
3595332    [Q145]
Name: nationality, dtype: object
1304370    [Q408]
Name: nationality, dtype: object
6023952    [Q784]
Name: nationality, dtype: object
8292117    [Q145]
Name: nationality, dtype: object
105391    [Q30]
Name: nationality, dtype: object
5807938    [Q30]
Name: nationality, dtype: object
3398004    [Q30]
Name: nationality, dtype: object
5721634    [Q30]
Name: nationality, dtype: object
8485287    [Q30]
Name: nationality, dtype: object
1271906    [Q30]
Name: nationality, dtype: object
1428757    [Q30]
Name: nationality, dtype: object
186410    [Q408]
Name: nationality, dtype: object
4680523    [Q30]
Name: nationality, dtype: object
1337817    [Q183]
Name: nationality, dtype: object
6833134    [Q30]
Name: nationality, dtype: object
3409344    [Q45]
Name: nationality, dtype: object
5958134    [Q30]
Name: nationality, dtype: object
6799555    [Q30]
Name: nationality, dtype: object
8108517    [Q30]
Name: nationality, dtype: object
6819124    [Q30]
Name: nationality, dtype: object
5676054    [Q215, Q83286, Q30]
Name: nationality, dtype: object
5972129    [Q778]
Name: nationality, dtype: object
7091555    [Q408]
Name: nationality, dtype: object
4841266    [Q30]
Name: nationality, dtype: object
3398719    [Q30]
Name: nationality, dtype: object
3538414    [Q30]
Name: nationality, dtype: object
3587944    [Q241]
Name: nationality, dtype: object
4530062    [Q30]
Name: nationality, dtype: object
4615467    [Q30]
Name: nationality, dtype: object
1193880    [Q30]
Name: nationality, dtype: object
2563489    [Q30]
Name: nationality, dtype: object
2267342    [Q30]
Name: nationality, dtype: object
8108948    [Q30]
Name: nationality, dtype: object
1195643    [Q30]
Name: nationality, dtype: object
1317648    [Q145]
Name: nationality, dtype: object
5676926    [Q30]
Name: nationality, dtype: object
433026    [Q30]
Name: nationality, dtype: object
5972129    [Q778]
Name: nationality, dtype: object
4630354    [Q30]
Name: nationality, dtype: object
1148829    [Q30]
Name: nationality, dtype: object
2661862    [Q778]
Name: nationality, dtype: object
4842574    [Q30]
Name: nationality, dtype: object
2267061    [Q30]
Name: nationality, dtype: object
1148829    [Q30]
Name: nationality, dtype: object
6813121    [Q30]
Name: nationality, dtype: object
4711351    [Q145, Q25]
Name: nationality, dtype: object
7961164    [Q30]
Name: nationality, dtype: object
4752133    [Q30]
Name: nationality, dtype: object
538996    [Q30]
Name: nationality, dtype: object
5868007    [Q30]
Name: nationality, dtype: object
7121258    [Q145]
Name: nationality, dtype: object
5972129    [Q778]
Name: nationality, dtype: object
2267894    [Q30]
Name: nationality, dtype: object
6894403    [Q30]
Name: nationality, dtype: object
4711942    [Q30]
Name: nationality, dtype: object
1147874    [Q30]
Name: nationality, dtype: object
5855272    [Q30]
Name: nationality, dtype: object
7125346    [Q664]
Name: nationality, dtype: object
4671177    [Q408]
Name: nationality, dtype: object
1172251    [Q30]
Name: nationality, dtype: object
377022    [Q145]
Name: nationality, dtype: object
1563407    [Q30]
Name: nationality, dtype: object
5910262    [Q20]
Name: nationality, dtype: object
4615467    [Q30]
Name: nationality, dtype: object
8094494    [Q30]
Name: nationality, dtype: object
1520738    [Q30]
Name: nationality, dtype: object
6805537    [Q16]
Name: nationality, dtype: object
324225    [Q30]
Name: nationality, dtype: object
7169806    [Q30]
Name: nationality, dtype: object
1144192    [Q30]
Name: nationality, dtype: object
2593964    [Q664]
Name: nationality, dtype: object
3692791    [Q30]
Name: nationality, dtype: object
3503413    [Q29, Q30]

In [6]:
with open('../extracted_country_counts/' + filename + '_code_count.json', 'w') as file_code_count:
    json.dump(dict_code_count, file_code_count)

In [7]:
dict_code_count

{'Q30': 1850,
 'Q145': 267,
 'Q408': 104,
 'Q45': 31,
 'Q96': 9,
 'Q29': 28,
 'Q1039': 4,
 'Q838261': 9,
 'Q183': 16,
 'Q664': 17,
 'Q27': 30,
 'Q16': 116,
 'Q778': 75,
 'Q766': 23,
 'Q414': 9,
 'Q800': 5,
 'Q717': 16,
 'Q244': 5,
 'Q34': 8,
 'Q1033': 3,
 'Q739': 4,
 'Q928': 6,
 'Q258': 20,
 'Q21': 2,
 'Q668': 13,
 'Q114': 4,
 'Q760': 5,
 'Q1183': 22,
 'Q790': 2,
 'Q298': 8,
 'Q142': 13,
 'Q155': 3,
 'Q32': 3,
 'Q786': 4,
 'Q784': 7,
 'Q215': 1,
 'Q241': 2,
 'Q20': 3,
 'Q174193': 5,
 'Q38': 5,
 'Q36': 4,
 'Q17': 2,
 'Q29999': 3,
 'Q736': 2,
 'Q1029': 2,
 'Q212': 1,
 'Q237': 5,
 'Q115': 1,
 'Q77': 2,
 'Q730': 1,
 'Q117': 2,
 'Q40': 3,
 'Q39': 7,
 'Q189': 6,
 'Q1140152': 2,
 'Q35': 3,
 'Q954': 1,
 'Q242': 4,
 'Q783': 2,
 'Q683': 2,
 'Q148': 9,
 'Q833': 2,
 'Q33': 3,
 'Q750': 1,
 'Q25305': 2,
 'Q25': 1,
 'Q801': 1,
 'Q757': 1,
 'Q15180': 1,
 'Q5785': 1,
 'Q733': 1,
 'Q781': 2,
 'Q826': 1,
 'Q28': 1,
 'Q865': 2,
 'Q43': 1}